### ISSUE TITLE
Rainbow screen appearing and nothing is happening 

### ISSUE THREAD

**Issue by chiptus** [maxtez-raspbaker/tezos-rpi3#3]
Thank you for this guide!

I just started installing my RPI3 using your fedora28 image. For some reason after downloading and writing the image on my sd card, the os isn't going up. There's a screen in rainbow colors and nothing is happening. The RPI shows a red light, but nothing else (connected usbs - keyboard, hd - doesn't work)

**Comment by chiptus** [comment]
Maybe there's a problem with the download? can you add hash for the file so I can validate my download?

Thanks

**Comment by chiptus** [comment]
by this (https://www.raspberrypi.org/forums/viewtopic.php?t=55464) I expect to find `kernel.img` in one of the partitions and none found.

**Comment by maxtez-raspbaker** [comment]
@chiptus 
my sincere apologies for the late reply, I don't seem to get a notification for issues posted here. Have you solved the problem? The image that I posted was an early version of F28 that was not fully compatible with RPI3 B+ (I assume that is the model you have). 
Perhaps the best option is to install a fresh Fedora minimal aarch64 from the official repository https://alt.fedoraproject.org/alt/
The current release is F29 while I have F28 but I should be able to help you out, let me know (email: maxtez.raspbaker@gmail.com).

**Comment by chiptus** [comment]
I've figured this out and installed F29, but for some reason I couldn't run the node. Instead I've installed raspabian and it works great

**Comment by maxtez-raspbaker** [comment]
great to hear it works, does raspbian support aarch64?
if you have time, please keep me posted, which network are you on? is
baking/endorsing running smoothly?
max
